### ISSUE TITLE
Submodule checkout fails - do you need to push to ibex_wb?

### ISSUE THREAD

**Issue by robinsonb5** [epsilon537/boxlambda#25]
Hi,

I saw this project via your Exit MIG, Enter LiteDRAM blog post, mentioned on HN.  It's really exciting to see so many build-your-own-computer-on-an-FPGA projects around these days, and I was keen to take a look and try it out - but the "make setup" step fails when checking out submodules, like so:
```
fatal: remote error: upload-pack: not our ref 5e3d258294478e1352edaba336b1c0640a188037
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'sub/ibex_wb', but it did not contain 5e3d258294478e1352edaba336b1c0640a188037. Direct fetching of that commit failed.
```
I guess you have work in your fork of ibex_wb that you haven't pushed yet?

**Comment by epsilon537** [comment]
Good catch! I forgot to push ibex_wb. Fixed now.
Thanks for letting me know!

**Comment by robinsonb5** [comment]
Awesome, thanks.

I also seem to be missing a couple of header files needed by projects/ddr_test -> make sim - namely sdram.h and memtest.h?
(If I had a penny for every time I've forgotten to check in a tiny but important file...!)

**Comment by epsilon537** [comment]
I'm going to have to up my game now that someone's actually trying to recreate the setup :-)
This one's less obvious to me though. Do you see the sub/litex directory after running make setup?
If so, do you see sub/litex/litex/soc/software/libbase/memtest.h as well?

I'll go through the build steps again in a clean clone, to cross-check.

**Comment by robinsonb5** [comment]
Ah - my apologies, the previous submodule error had left some of the submodule directories unpopulated.  (And rather unhelpfully a git submodule update --init --recursive does nothing - I had to visit them in turn and do a git checkout!)

**Comment by epsilon537** [comment]
That's good to know. I'll see if I can make 'make setup' more robust.

**Comment by epsilon537** [comment]
I will run the build checks in a clean clone prior to release to avoid these issues.
